    function makePostApplications(image, fName,lName, content, elementID,numLikes,numReplies,numShares){
        /* ----- generate posts --- */
        $('#wall-dataF').append('<div class="panel-body wallPosts"><div class="media"><a class="pull-left" href="#"><img style="height:40px;" id="img'+elementID+'" class="media-object img-rounded" src=""></a><div class="dropdown pull-right"><a class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-cog"></span><span class="caret"></span></a><ul class="dropdown-menu" style="min-width: 0px !important; padding:0px !important;"><li><a class="dropdown-item editEntry" data-toggle="modal" data-target="#edit-modal'+elementID+'"><H6>Edit</H6></a></li><li><a class="dropdown-item deleteEntry" data-toggle="modal" data-target="#delete-modal'+elementID+'"><H6>Delete</H6></a></li></ul></div><div class="media-body"><h6 class="post-time pull-right text-muted time" style="padding-right:4px;"> X minutes ago</h6><h5 class="post-name mt-0" style="color:cadetblue;"><a href="#">'+fName+" "+lName+'</a></h5><p class="post-message" style="word-spacing: 0px;">'+readRuneArrayThatWorks(content)+'</p></div><ul><li><a class="btn btn-sm like-btn" id =like-btn'+elementID+'><img class="like-btn-ico" src="/ustart_front/ico/like.png">  <p class="mt-0" style="color:cadetblue; display:inline;">'+numLikes+'</p></a></li><li><a class="btn btn-sm comment-btn" id="'+elementID+'" data-toggle="modal" data-target="#main-modal'+elementID+'"><img class="coment-btn-ico" src="/ustart_front/ico/no comment.png">  <p class="mt-0" style="color:cadetblue; margin-left:1px; display:inline;">'+ numReplies+'</p></a></li><li><a class="btn btn-sm share-btn" data-toggle="modal" data-target="#share-modal'+elementID+'"><span><img class="share-btn-ico" src="/ustart_front/ico/not share.png"><p class="mt-0" style="margin-left:1px; color:cadetblue; display:inline;">'+numShares+'</p></span></a></li></ul></div>');
        $("#img"+elementID).attr("src", image);
        /* ----- end generate posts --- */
        /* ----- append share modals --- */
        $('#shareModals').append('<div class="modal fade" id="share-modal'+elementID+'" role="dialog"><div class="modal-dialog"><div class="modal-content"><div class="modal-header"><button type="button" class="close" data-dismiss="modal">&times;</button><h4 class="modal-title">Share On Your Profile</h4></div><div class="modal-body"><div class="media"><a class="pull-left" href="#"><img class="media-object img-rounded" id="share-img'+elementID+'"src=""></a><div class="media-body"><h6 class="pull-right text-muted time">X minute ago</h6><h5 class="mt-0" style="color:cadetblue;">'+fName+" "+lName+'</h5><p>'+readRuneArrayThatWorks(content)+'</p></div></div><br><div class="form-group"><form class="shareCommentForm"><textarea class="form-control" id="comment-msg" placeholder="Say Something about this..."></textarea><button class="btn btn-primary" onclick=" $(this).closest("form").submit();">Post</button></form></div></div></div></div></div>');
        $("#share-img"+elementID).attr("src", image);
        /* ----- end append share modals --- */
        /* ----- append edit modals --- */
        $('#editModals').append('<div class="modal fade" id="edit-modal'+elementID+'" role="dialog"><div class="modal-dialog"><div class="modal-content"><div class="modal-header"><button type="button" class="close" data-dismiss="modal">&times;</button><h4 class="modal-title">Edit Post</h4></div><div class="modal-body"><div class="media"><a class="pull-left" href="#"><img class="media-object img-rounded" id="edit-img'+elementID+'" src=""></a><div class="media-body"><div class="form-group"><form id="Edit-Post-Form"><textarea class="form-control" style="resize:none;" placeholder="">'+readRuneArrayThatWorks(content)+'</textarea></form></div></div></div></div><div class="modal-footer"><button id="edit-postSubmit" class="btn btn-primary pull-right">Post</button></div></div></div></div>');
        $("#edit-img"+elementID).attr("src", image);
        /* ----- end append edit modals --- */
         /* ----- append delete modals --- */
         $('#deleteModals').append('<div class="modal fade" id="delete-modal'+elementID+'" role="dialog"><div class="modal-dialog"><div class="modal-content"><div class="modal-header"><span style="font-size:20px;">Confirm Deletion</span></div><div class="modal-body"><span style="font-size:15px;">Are you sure you want to delete this post?</span></div> <div class="modal-footer"><form action ="http://ustart.today:'+port+'/deletePost" method ="POST"><input type="hidden" name="postid" value=(this).attr("id")><button class="btn btn-danger btn-ok" type="submit">Delete</button><button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button></form></div></div></div></div>');
         /* ----- end append delete modals --- */
        /*--- append main modal ---- */
        $('#commentModals').append('<div class="modal fade" id="main-modal'+elementID+'" role="dialog"><div class="modal-dialog"><div class="modal-content"><div class="modal-header"><button type="button" class="close" data-dismiss="modal">&times;</button><div class="media"> <a class="pull-left" href="#"><img class="media-object img-rounded" id="comment-img'+elementID+'" src=""> </a><div class="media-body"><h6 class="pull-right text-muted time"></h6><h5 class="mt-0" style="color:cadetblue;">'+fName+" "+lName+'</h5><p>'+readRuneArrayThatWorks(content)+'</p></div></div></div><div class="modal-body"><div class="input-group"><textarea style="resize: none;" class="form-control" id="commentContent'+elementID+'" name="commentz" placeholder="Add a comment" aria-label="With textarea"></textarea><span class="input-group-addon new-comment-submit" id="'+elementID+'"><i class="fa fa-edit"></i></span></div><br><div id="comments-list'+elementID+'"></div>');
        
        $("#comment-img"+elementID).attr("src", image);
         /* ----- end append main modals --- */
    }

     function makeCommentApplications(parentID, image, fName,lName, content, postID,numReplies){
         $('#comments-list'+parentID).append('<div class="media"><h6 class="pull-right text-muted time">X minutes ago</h6><a class="media-left" href="#"><img style="height:40px;" id="comment-element'+postID+'" class="img-rounded" src=""></a><div class="media-body"><h5 class="media-heading user_name" style="color:cadetblue;">'+fName+" "+lName+'</h5><p>'+readRuneArrayThatWorks(content)+'</p><p><small><a class="comment-like">Like</a></small> -<small><a class="confirmation-callback">Remove</a></small></p>');
        if(numReplies > 0){
             $('#comments-list'+parentID).append('<p><small><a class="view-replies">View '+numReplies+' Replies</a></small></p>');
        }
         else{
              $('#comments-list'+parentID).append('<div class="commentOfComment" id="replies'+postID+'"></div></div><div class="input-group"><input type = "hidden" name="postID" value= "'+postID+'"><input class="form-control" placeholder="Add a reply" type="text" name="body"><span class="input-group-addon new-comment-o-comment-submit" placeholder="Add a comment" id="'+postID+'"><i class="fa fa-edit"></i></span></div></div>');
         }
                                           
         $("#comment-element"+postID).attr("src", image);
     }

     function makeNewCommentApplications(parentID, image, fName,lName, content, postID,numReplies){
         if(numReplies > 0){
         $('#comments-list'+parentID).prepend('<div class="media"><h6 class="pull-right text-muted time">X minutes ago</h6><a class="media-left" href="#"><img style="height:40px;" id="comment-element'+postID+'" class="img-rounded" src=""></a><div class="media-body"><h5 class="media-heading user_name" style="color:cadetblue;">'+fName+" "+lName+'</h5><p>'+readRuneArrayThatWorks(content)+'</p><p><small><a class="comment-like">Like</a></small> -<small><a class="confirmation-callback">Remove</a></small></p><p><small><a class="view-replies">View '+numReplies+' Replies</a></small></p><div class="commentOfComment" id="replies'+postID+'"></div></div><div class="input-group"><form id="innercommentform" method="POST" action="/AddComment2"><input type = "hidden" name="postID" value= "'+postID+'"><input class="form-control" placeholder="Add a reply" type="text" name="body"></form><span class="input-group-addon"><a onclick="$(this).closest("form").submit();"><i class="fa fa-edit"></i></a></span></div></div>');
         }
         else{
             $('#comments-list'+parentID).prepend('<div class="media"><h6 class="pull-right text-muted time">X minutes ago</h6><a class="media-left" href="#"><img style="height:40px;" id="comment-element'+postID+'" class="img-rounded" src=""></a><div class="media-body"><h5 class="media-heading user_name" style="color:cadetblue;">'+fName+" "+lName+'</h5><p>'+readRuneArrayThatWorks(content)+'</p><p><small><a class="comment-like">Like</a></small> -<small><a class="confirmation-callback">Remove</a></small></p><div class="commentOfComment" id="replies'+postID+'"></div></div><div class="input-group"><form id="innercommentform" method="POST" action="/AddComment2"><input type = "hidden" name="postID" value= "'+postID+'"><input class="form-control" placeholder="Add a reply" type="text" name="body"></form><span class="input-group-addon"><a onclick="$(this).closest("form").submit();"><i class="fa fa-edit"></i></a></span></div></div>');
             
         }                               
         $("#comment-element"+postID).attr("src", image);
     }


    function makeCommentOfCommentsApplications(){
    }

    function makeNewPostApplications(image, fName,lName, content, elementID,numLikes,numReplies,numShares){
        /* ----- generate posts --- */
        $('#wall-dataF').prepend('<div class="panel-body wallPosts"><div class="media"><a class="pull-left" href="#"><img style="height:40px;" id="img'+elementID+'" class="media-object img-rounded" src=""></a><div class="dropdown pull-right"><a class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-cog"></span><span class="caret"></span></a><ul class="dropdown-menu" style="min-width: 0px !important; padding:0px !important;"><li><a class="dropdown-item editEntry" data-toggle="modal" data-target="#edit-modal'+elementID+'"><H6>Edit</H6></a></li><li><a class="dropdown-item deleteEntry" data-toggle="modal" data-target="#delete-modal'+elementID+'"><H6>Delete</H6></a></li></ul></div><div class="media-body"><h6 class="post-time pull-right text-muted time" style="padding-right:4px;"> X minutes ago</h6><h5 class="post-name mt-0" style="color:cadetblue;"><a href="#">'+fName+" "+lName+'</a></h5><p class="post-message" style="word-spacing: 0px;">'+readRuneArrayThatWorks(content)+'</p></div><ul><li><a class="btn btn-sm like-btn" id =like-btn'+elementID+'><img class="like-btn-ico" src="/ustart_front/ico/like.png">  <p class="mt-0" style="color:cadetblue; display:inline;">'+numLikes+'</p></a></li><li><a class="btn btn-sm comment-btn" id="'+elementID+'" data-toggle="modal" data-target="#main-modal'+elementID+'"><img class="coment-btn-ico" src="/ustart_front/ico/no comment.png">  <p class="mt-0" style="color:cadetblue; margin-left:1px; display:inline;">'+ numReplies+'</p></a></li><li><a class="btn btn-sm share-btn" data-toggle="modal" data-target="#share-modal'+elementID+'"><span><img class="share-btn-ico" src="/ustart_front/ico/not share.png"><p class="mt-0" style="margin-left:1px; color:cadetblue; display:inline;">'+numShares+'</p></span></a></li></ul></div>');
        $("#img"+elementID).attr("src", image);
        /* ----- end generate posts --- */
        /* ----- append share modals --- */
        $('#shareModals').append('<div class="modal fade" id="share-modal'+elementID+'" role="dialog"><div class="modal-dialog"><div class="modal-content"><div class="modal-header"><button type="button" class="close" data-dismiss="modal">&times;</button><h4 class="modal-title">Share On Your Profile</h4></div><div class="modal-body"><div class="media"><a class="pull-left" href="#"><img class="media-object img-rounded" id="share-img'+elementID+'"src=""></a><div class="media-body"><h6 class="pull-right text-muted time">X minute ago</h6><h5 class="mt-0" style="color:cadetblue;">'+fName+" "+lName+'</h5><p>'+readRuneArrayThatWorks(content)+'</p></div></div><br><div class="form-group"><form class="shareCommentForm"><textarea class="form-control" id="comment-msg" placeholder="Say Something about this..."></textarea><button class="btn btn-primary" onclick=" $(this).closest("form").submit();">Post</button></form></div></div></div></div></div>');
        $("#share-img"+elementID).attr("src", image);
        /* ----- end append share modals --- */
        /* ----- append edit modals --- */
        $('#editModals').append('<div class="modal fade" id="edit-modal'+elementID+'" role="dialog"><div class="modal-dialog"><div class="modal-content"><div class="modal-header"><button type="button" class="close" data-dismiss="modal">&times;</button><h4 class="modal-title">Edit Post</h4></div><div class="modal-body"><div class="media"><a class="pull-left" href="#"><img class="media-object img-rounded" id="edit-img'+elementID+'" src=""></a><div class="media-body"><div class="form-group"><form id="Edit-Post-Form"><textarea class="form-control" style="resize:none;" placeholder="">'+readRuneArrayThatWorks(content)+'</textarea></form></div></div></div></div><div class="modal-footer"><button id="edit-postSubmit" class="btn btn-primary pull-right">Post</button></div></div></div></div>');
        $("#edit-img"+elementID).attr("src", image);
        /* ----- end append edit modals --- */
         /* ----- append delete modals --- */
         $('#deleteModals').append('<div class="modal fade" id="delete-modal'+elementID+'" role="dialog"><div class="modal-dialog"><div class="modal-content"><div class="modal-header"><span style="font-size:20px;">Confirm Deletion</span></div><div class="modal-body"><span style="font-size:15px;">Are you sure you want to delete this post?</span></div> <div class="modal-footer"><form action ="http://ustart.today:'+port+'/deletePost" method ="POST"><input type="hidden" name="postid" value=(this).attr("id")><button class="btn btn-danger btn-ok" type="submit">Delete</button><button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button></form></div></div></div></div>');
         /* ----- end append delete modals --- */
        /*--- append main modal ---- */
        $('#commentModals').append('<div class="modal fade" id="main-modal'+elementID+'" role="dialog"><div class="modal-dialog"><div class="modal-content"><div class="modal-header"><button type="button" class="close" data-dismiss="modal">&times;</button><div class="media"> <a class="pull-left" href="#"><img class="media-object img-rounded" id="comment-img'+elementID+'" src=""> </a><div class="media-body"><h6 class="pull-right text-muted time"></h6><h5 class="mt-0" style="color:cadetblue;">'+fName+" "+lName+'</h5><p>'+readRuneArrayThatWorks(content)+'</p></div></div></div><div class="modal-body"><div class="input-group"><textarea style="resize: none;" class="form-control" id="commentContent'+elementID+'" name="commentz" placeholder="Add a comment" aria-label="With textarea"></textarea><span class="input-group-addon new-comment-submit" id="'+elementID+'"><i class="fa fa-edit"></i></span></div><br><div id="comments-list'+elementID+'"></div>');
        $("#comment-img"+elementID).attr("src", image);
         /* ----- end append main modals --- */
    }

    
